import { darken, lighten, type PaletteOptions } from '@mui/material';
import {
  black,
  darkBackgroundDefault,
  darkBackgroundPaper,
  darkErrorMain,
  darkInfoMain,
  darkPrimaryMain,
  darkSecondaryMain,
  darkSuccessMain,
  darkTextPrimary,
  darkTextSecondary,
  darkWarningMain,
  grey100,
  grey200,
  grey300,
  grey400,
  grey50,
  grey500,
  grey600,
  grey700,
  grey800,
  grey900,
  white,
} from './colors';

export const darkPalette: PaletteOptions = {
  mode: 'dark',
  primary: {
    main: darkPrimaryMain,
    light: lighten(darkPrimaryMain, 0.2),
    dark: darken(darkPrimaryMain, 0.1),
    contrastText: white,
  },
  secondary: {
    main: darkSecondaryMain,
    light: lighten(darkSecondaryMain, 0.25),
    dark: darken(darkSecondaryMain, 0.1),
    contrastText: black,
  },
  background: {
    default: darkBackgroundDefault,
    paper: darkBackgroundPaper,
  },
  success: {
    main: darkSuccessMain,
    light: lighten(darkSuccessMain, 0.2),
    dark: darken(darkSuccessMain, 0.1),
    contrastText: black,
  },
  error: {
    main: darkErrorMain,
    light: lighten(darkErrorMain, 0.2),
    dark: darken(darkErrorMain, 0.1),
    contrastText: black,
  },
  info: {
    main: darkInfoMain,
    light: lighten(darkInfoMain, 0.2),
    dark: darken(darkInfoMain, 0.1),
    contrastText: black,
  },
  warning: {
    main: darkWarningMain,
    light: lighten(darkWarningMain, 0.2),
    dark: darken(darkWarningMain, 0.1),
    contrastText: black,
  },
  text: {
    primary: darkTextPrimary,
    secondary: darkTextSecondary,
  },
  grey: {
    50: grey50,
    100: grey100,
    200: grey200,
    300: grey300,
    400: grey400,
    500: grey500,
    600: grey600,
    700: grey700,
    800: grey800,
    900: grey900,
  },
};
