import { lighten, darken, type PaletteOptions } from '@mui/material/styles';
import {
  black,
  grey100,
  grey200,
  grey300,
  grey400,
  grey50,
  grey500,
  grey600,
  grey700,
  grey800,
  grey900,
  lightBackgroundDefault,
  lightBackgroundPaper,
  lightErrorMain,
  lightInfoMain,
  lightPrimaryMain,
  lightSecondaryMain,
  lightSuccessMain,
  lightTextPrimary,
  lightTextSecondary,
  lightWarningMain,
  white,
} from './colors';

export const lightPalette: PaletteOptions = {
  mode: 'light',
  primary: {
    main: lightPrimaryMain,
    light: lighten(lightPrimaryMain, 0.9),
    dark: darken(lightPrimaryMain, 0.1),
    contrastText: black,
  },
  secondary: {
    main: lightSecondaryMain,
    light: lighten(lightSecondaryMain, 0.85),
    dark: darken(lightSecondaryMain, 0.1),
    contrastText: black,
  },
  background: {
    default: lightBackgroundDefault,
    paper: lightBackgroundPaper,
  },
  success: {
    main: lightSuccessMain,
    light: lighten(lightSuccessMain, 0.8),
    dark: darken(lightSuccessMain, 0.1),
    contrastText: black,
  },
  error: {
    main: lightErrorMain,
    light: lighten(lightErrorMain, 0.8),
    dark: darken(lightErrorMain, 0.1),
    contrastText: white,
  },
  info: {
    main: lightInfoMain,
    light: lighten(lightInfoMain, 0.8),
    dark: darken(lightInfoMain, 0.1),
    contrastText: black,
  },
  warning: {
    main: lightWarningMain,
    light: lighten(lightWarningMain, 0.8),
    dark: darken(lightWarningMain, 0.1),
    contrastText: black,
  },
  text: {
    primary: lightTextPrimary,
    secondary: lightTextSecondary,
  },
  grey: {
    50: grey50,
    100: grey100,
    200: grey200,
    300: grey300,
    400: grey400,
    500: grey500,
    600: grey600,
    700: grey700,
    800: grey800,
    900: grey900,
  },
};
